# Configuration file for UHABS simulation

# Initial currents map
init_map: ./data/S1A_ESA_159.56W_20.87N_VV_C5_GFS05CDF_wind_level2.nc

# Navigation time step, how ofted do we sample for new paths
nav_timestep: 100

# Simulation speed up factor, for realtime simulation use 1
sim_speedup_factor: 10


# Realtime frequency of telemetry sampling
telem_freq: 50

# Initial propulsion (m/s), and location (lat, lon)
init_propulstion: 5
init_pos: [20.2, -158.7]

# Desired destination
destination: [21.05, -160.0]

# Comms
boat_addr: thinkmachine
gs_addr: thinkmachine


ports:
  nav_path:     15001
  telem:        15002
  gps:          15003
  manual_az:    15004
  manual_prop:  15005
  maps:         15006

